data:
  image: borgius/data
  volumes:
    - ./data:/data
    - /var/run:/data/run

dnsmasq:
    image: andyshinn/dnsmasq
    ports:
        - "53:53"
        - "53:53/udp"
    cap_add:
        - NET_ADMIN
#    volumes:
#        - ./data/config/dnsmasq.conf:/etc/dnsmasq.conf
    command: -S /dev/192.168.99.100

pgsql:
  image: borgius/pgsql
  volumes_from:
      - data
  environment:
    PGDATA: /data/pgsql
    POSTGRES_DB: mydb
    POSTGRES_USER: me
    POSTGRES_PASSWORD: password
  ports:
    - "5432:5432"

beanstalkd:
  image: chriskite/beanstalkd
  ports:
    - "11300:11300"
  volumes_from:
    - data
  volumes:
    - ./data/beanstalkd:/data

couchbase:
  image: couchbase/server
  ports:
    - "8091:8091"
    - "8092:8093"
    - "8093:8093"
  volumes_from:
    - data
  volumes:
    - ./data/couchbase:/opt/couchbase/var

php:
  image: borgius/php-phalcon
  volumes_from:
    - data
  links:
    - pgsql
    - beanstalkd
    - couchbase

nginx:
  image: borgius/nginx
  volumes_from:
    - data
  links:
    - php
  ports:
    - "80:80"
