#!/bin/sh
#. ./shellinit.sh
$(boot2docker shellinit 2> /dev/null)
root=$(realpath $(dirname $(readlink $0))/..)
p=$(echo $PWD | sed "s#$root##g")
cid=$(docker ps |grep php| cut -c1-12)
docker exec -ti $cid bash -c "cd $p && php $1 $2 $3 $4"